services:
  - type: web
    name: diatrack
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DATABASE_URL
        fromDatabase:
          name: diatrack-db
          property: connectionString

databases:
  - name: diatrack-db
    databaseName: diatrack
    user: diatrack